version: "3"
services:
  web1:
    image: nginx:alpine
    container_name: web1
    restart: always
    volumes:
      - ./service1/nginx.conf:/etc/nginx/nginx.conf
      - ./service1/index.html:/usr/share/nginx/html/index.html
    ports:
      - "8080:80"
    networks:
      - web
  web2:
    image: nginx:alpine
    container_name: web2
    restart: always
    volumes:
      - ./service2/nginx.conf:/etc/nginx/nginx.conf
      - ./service2/index.html:/usr/share/nginx/html/index.html
    ports:
      - "8081:80"
    networks:
      - web
  web3:
    image: nginx:alpine
    container_name: web3
    restart: always
    volumes:
      - ./service3/nginx.conf:/etc/nginx/nginx.conf
      - ./service3/index.html:/usr/share/nginx/html/index.html
    ports:
      - "8082:80"
    networks:
      - web
  proxy1:
    image: nginx:alpine
    container_name: proxy
    restart: always
    depends_on:
      - web1
      - web2
      - web3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "5007:5007"
    networks:
      - web
networks:
  web:
    driver: bridge
